[package]
name = "oz_erc20"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", branch = "release-v0.10.0" }
starknet = "2.5.3"

[[target.starknet-contract]]