[package]
name = "blockifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# This is how they instructed to use their package.
cairo-rs =  { git = "https://github.com/lambdaclass/cairo-rs.git" }
anyhow = "1.0.66"

[dev-dependencies]
pretty_assertions = "1.2.1"
